CREATE DATABASE IF NOT EXISTS tour_details;
USE tour_details;

CREATE TABLE IF NOT EXISTS users (
  id int NOT NULL AUTO_INCREMENT,
  user_id varchar(20) NOT NULL UNIQUE,
  password varchar(255) NOT NULL,
  role enum('admin','department') NOT NULL DEFAULT 'department',
  department_name varchar(100) DEFAULT NULL,
  status enum('active','inactive') NOT NULL DEFAULT 'active',
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY role (role),
  KEY status (status)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;;

CREATE TABLE IF NOT EXISTS employees (
  id int NOT NULL AUTO_INCREMENT,
  sap_id varchar(8) NOT NULL UNIQUE,
  name varchar(100) NOT NULL,
  email varchar(150) NOT NULL UNIQUE,
  designation varchar(100) NOT NULL,
  grade varchar(20) NOT NULL,
  department varchar(100) NOT NULL,
  status enum('active','inactive') NOT NULL DEFAULT 'active',
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY status (status)
  
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS employee_otps (
  id int NOT NULL AUTO_INCREMENT,
  employee_id int NOT NULL,
  otp_code varchar(6) NOT NULL,
  expires_at timestamp NOT NULL,
  used_at timestamp NULL DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_employee_created (employee_id, created_at),
  KEY idx_employee_otp (employee_id, otp_code, used_at, expires_at),
  CONSTRAINT employee_otps_employee_fk FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;;

CREATE TABLE IF NOT EXISTS master_grades (
  id int NOT NULL AUTO_INCREMENT,
  grade_name varchar(20) NOT NULL UNIQUE,
  status enum('active','inactive') NOT NULL DEFAULT 'active',
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_status_grade (status, grade_name)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;;

CREATE TABLE IF NOT EXISTS master_departments (
  id int NOT NULL AUTO_INCREMENT,
  department_name varchar(100) NOT NULL UNIQUE,
  status enum('active','inactive') NOT NULL DEFAULT 'active',
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_status_department (status, department_name)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;;

CREATE TABLE IF NOT EXISTS master_destinations (
  id int NOT NULL AUTO_INCREMENT,
  destination_name varchar(150) NOT NULL UNIQUE,
  status enum('active','inactive') NOT NULL DEFAULT 'active',
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_status_destination (status, destination_name)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;;

CREATE TABLE IF NOT EXISTS tour_reports (
  id int NOT NULL AUTO_INCREMENT,
  employee_id int DEFAULT NULL,
  sap_id varchar(8) NOT NULL,
  name varchar(100) DEFAULT NULL,
  designation varchar(100) DEFAULT NULL,
  grade varchar(20) DEFAULT NULL,
  department varchar(100) DEFAULT NULL,
  tour_type varchar(50) DEFAULT NULL,
  purpose varchar(255) DEFAULT NULL,
  referred_hospital_name varchar(150) DEFAULT NULL,
  medical_reference_no varchar(100) DEFAULT NULL,
  medical_reference_date date DEFAULT NULL,
  patient_name varchar(100) DEFAULT NULL,
  patient_relation varchar(50) DEFAULT NULL,
  escort_employee_sap_id varchar(8) DEFAULT NULL,
  return_vehicle_required enum('Yes','No') DEFAULT NULL,
  railway_availability varchar(255) DEFAULT NULL,
  leave_availed enum('Yes','No') DEFAULT NULL,
  leave_details varchar(255) DEFAULT NULL,
  leave_start_date date DEFAULT NULL,
  leave_end_date date DEFAULT NULL,
  start_date date DEFAULT NULL,
  start_time time DEFAULT NULL,
  start_place varchar(150) DEFAULT NULL,
  end_date date DEFAULT NULL,
  end_time time DEFAULT NULL,
  destination varchar(150) DEFAULT NULL,
  mode_of_travel varchar(50) DEFAULT NULL,
  weekly_off varchar(20) DEFAULT NULL,
  approving_authority varchar(100) DEFAULT NULL,
  approval_note_path varchar(255) DEFAULT NULL,
  approval_note_name varchar(255) DEFAULT NULL,
  combined_pdf_path varchar(255) DEFAULT NULL,
  combined_pdf_name varchar(255) DEFAULT NULL,
  status enum('Draft','Pending','Approved','Rejected') NOT NULL DEFAULT 'Draft',
  rejection_reason text DEFAULT NULL,
  approved_by int DEFAULT NULL,
  approved_at timestamp NULL DEFAULT NULL,
  submitted_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY sap_id (sap_id),
  KEY status (status),
  KEY start_date (start_date),
  KEY employee_id (employee_id),
  KEY approved_by (approved_by),

KEY idx_sap_created (sap_id, created_at),
KEY idx_sap_status (sap_id, status),
KEY idx_department_created (department, created_at),
KEY idx_dept_sap_status (department, sap_id, status),
KEY idx_status_startdate (status, start_date),
  CONSTRAINT tour_reports_employee_fk FOREIGN KEY (employee_id) REFERENCES employees(id),
  CONSTRAINT tour_reports_user_fk FOREIGN KEY (approved_by) REFERENCES users(id)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;;

CREATE TABLE IF NOT EXISTS tour_supporting_documents (
  id int NOT NULL AUTO_INCREMENT,
  tour_report_id int NOT NULL,
  file_name varchar(255) NOT NULL,
  file_path varchar(255) NOT NULL,
  file_type varchar(100) DEFAULT NULL,
  uploaded_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY tour_report_id (tour_report_id),
  CONSTRAINT support_docs_report_fk FOREIGN KEY (tour_report_id) REFERENCES tour_reports(id) ON DELETE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;;

INSERT IGNORE INTO master_grades (grade_name)
VALUES
  ('RS01-Workmen'), ('RS02-Workmen'), ('RS03-Workmen'), ('RS04-Workmen'), ('RS05-Workmen'), ('RS06-Workmen'), ('RS07-Workmen'), ('RS08-Workmen'), ('RS09-Workmen'), ('RS10-Workmen'),
  ('JO-Junior Officer'), ('ET-Executive Trainee'),
  ('M02-JM'), ('M03-AM'), ('M04-DM'), ('M05-Mgr'), ('M06-SM'), ('M07-AGM'), ('M08-DGM'), ('M09-GM'), ('M10-CGM'), ('M11-ED');

IINSERT INTO master_departments (department_name)
VALUES
('C&IT'),
('Chemical Lab'),
('CIVIL'),
('CIVIL-Civil Maint O/T'),
('CIVIL-Civil Maint.Ht'),
('CIVIL-Civil Office'),
('CIVIL-W/S(T/S,Kdl)'),
('Contract'),
('CSR'),
('ELECT SERVICES-ERS'),
('ELECT SERVICES-KDL,SSA'),
('ELECT SERVICES-TS/MSS'),
('ELECT SERVICES'),
('ELECT SERVICES-FES-11B'),
('ELECT SERVICES-FES-11C'),
('ELECT SERVICES-FES-14'),
('ELECT SERVICES-Telephone'),
('Finance'),
('Geology-Prod.Plg'),
('Geology-Geology-11C'),
('Geology-Geology-14'),
('Geology-Q.Control'),
('HOP Sectt.'),
('Hospital'),
('HR'),
('IE'),
('M&S'),
('Material Management-C.S.D.,KDL'),
('Material Management-CSD HT'),
('Material Management'),
('MECH. SERVICES-Auto Shop'),
('MECH. SERVICES-FRS-11C'),
('MECH. SERVICES-FRS-14'),
('MECH. SERVICES-FRS-11B'),
('MECH. SERVICES-HRS-14'),
('MECH. SERVICES-HEM,KDL'),
('MECH. SERVICES-M/C Shop'),
('MECH. SERVICES-S.M.Office'),
('MECH. SERVICES-SC-11C'),
('MECH. SERVICES-Transport'),
('MINING 11B-Drilling'),
('MINING 11B-Excavation'),
('MINING 11B-Haulage'),
('MINING 11B-Mining'),
('MINING 11B-Miscellaneous'),
('MINING 11C-Drilling'),
('MINING 11C-Excavation'),
('MINING 11C-Haulage'),
('MINING 11C-Mining'),
('MINING 11C-Miscellaneous'),
('MINING 14-Drilling'),
('MINING 14-Excavation'),
('MINING 14-Haulage'),
('MINING 14-Mining'),
('MINING 14-Miscellaneous'),
('MINING-Blasting'),
('MINING-Hod & Sect'),
('MINING-Kumhar Marenga'),
('MINING-Mine Office 14'),
('MINING-Mine Planning cell'),
('PLANT (ELECT.)-CP&DH(E)-11B'),
('PLANT (ELECT.)-CP&DH(E)-14'),
('PLANT (ELECT.)-CP(E)-11C'),
('PLANT (ELECT.)-DH(E)-11C'),
('PLANT (ELECT.)-LP(E)'),
('PLANT (ELECT.)-SP-I(E)'),
('PLANT (ELECT.)-SP-II(E)'),
('PLANT (MECH.)-CP&DH(M)-11B'),
('PLANT (MECH.)-CP(M)-11C'),
('PLANT (MECH.)-CP(M)-14'),
('PLANT (MECH.)-DH(M)-11C'),
('PLANT (MECH.)-DH(M)-14'),
('PLANT (MECH.)-LP(M)'),
('PLANT (MECH.)-Plant Office'),
('PLANT (MECH.)-SP-I(M)'),
('PLANT (MECH.)-SP-II(M)'),
('Production'),
('School'),
('Survey-11C'),
('T&S,E-Trg.Inst'),
('T&S,E-Environment'),
('Vigilance'),
('Works');


INSERT INTO employees (
    sap_id,
    name,
    email,
    designation,
    grade,
    department
) VALUES 
('10000425','K Govind Raj','govindraj@nmdc.co.in','Jr.Officer','JO-Junior Officer','PLANT (ELECT.)-CP(E)-11C'),
('10000511','Rameshwar Pandey','pandey1248@nmdc.co.in','Senior Manager','M06-SM','MINING-Hod & Sect'),
('10000787','Sanjay Kumar Kochar','skkochar@nmdc.co.in','General Manager','M09-GM','MINING-Hod & Sect'),
('10000808','Kishan Ahuja','kishanahuja@nmdc.co.in','Chief General Manager','M10-CGM','Works'),
('10000813','Subramonian M','msubramonian@nmdc.co.in','General Manager','M09-GM','PLANT (MECH.)-Plant Office'),
('10000814','Rabindra Narayan','rnarayan@nmdc.co.in','Executive Director','M11-ED','HOP Sectt.'),
('10000815','Punguluri Prasad','prasadp@nmdc.co.in','General Manager','M09-GM','M&S'),
('10000846','Manish Kumar Goyal','mkgoyal@nmdc.co.in','Asst.General Manager','M07-AGM','C&IT'),
('10000886','K. Ilango','kilango@nmdc.co.in','Dy.General Manager','M08-DGM','Material Management'),
('10000954','M.A.E.Prasada Rao','prasadarao@nmdc.co.in','Asst.General Manager','M07-AGM','Works'),
('10000956','V.Bhavani Shankar','vbhavanishankar@nmdc.co.in','Manager','M05-Mgr','C&IT'),
('10000966','Madugula Nageswara Rao','nageswararao@nmdc.co.in','Manager','M05-Mgr','PLANT (MECH.)-CP(M)-14'),
('10001037','Govind Narayan Dohare','gndohare@nmdc.co.in','Manager','M05-Mgr','Works'),
('10001039','Kanta Jhadi','kanta.jhadi@nmdc.co.in','Jr.Officer','JO-Junior Officer','Finance'),
('10001068','Sudesh Kumar Singh Chandra','skschandra@nmdc.co.in','Dy.General Manager','M08-DGM','PLANT (MECH.)-Plant Office'),
('10001103','Pradeep Kumar Singh','pradeepks@nmdc.co.in','Asst.General Manager','M07-AGM','Works'),
('10001113','Donekal Rayalli Venkatesulu','drvenkat@nmdc.co.in','Dy.General Manager','M08-DGM','M&S'),
('10001119','Pradeep Morashia','pmorasia@nmdc.co.in','General Manager','M09-GM','Works'),
('10001120','Rajesh Kumar','rajeshkumar@nmdc.co.in','Dy.General Manager','M08-DGM','T&S,E-Trg.Inst'),
('10001122','B Selva Kumar','bselvakumar@nmdc.co.in','General Manager','M09-GM','MECH. SERVICES-S.M.Office'),
('10001138','Bhoj Kumar Kalihari','bhojkumar@nmdc.co.in','Senior Manager','M06-SM','Works'),
('10001163','K Thejeshwar Rao','thejeshwar@nmdc.co.in','Assistant Manager','M03-AM','HR'),
('10001235','Nirbhay Singh Markam','nsmarkam@nmdc.co.in','Asst.General Manager','M07-AGM','T&S,E-Trg.Inst'),
('10001238','Parambaloth Brian Antony','antony@nmdc.co.in','General Manager','M09-GM','Material Management'),
('10001293','Sibasish Guha','sguha@nmdc.co.in','Dy.General Manager','M08-DGM','Finance'),
('10001326','Shivraj Singh  Baghel','ssbaghel@nmdc.co.in','Manager','M05-Mgr','Works'),
('10001339','Prashant Kumar Biswas','prashantbiswas@nmdc.co.in','Jr.Officer','JO-Junior Officer','PLANT (MECH.)-CP&DH(M)-11B'),
('10001348','Sunil Kumar','sunilk@nmdc.co.in','Dy.General Manager','M08-DGM','T&S,E-Trg.Inst'),
('10001354','Dashmani Bhagat','dbhagat1969@gmail.com','Jr.Officer','JO-Junior Officer','Hospital'),
('10001446','Vaddi Madhusudhana','vmadhusudhana@nmdc.co.in','General Manager','M09-GM','Contract'),
('10001447','G Naresh Kumar','gnaresh@nmdc.co.in','Dy.General Manager','M08-DGM','Works'),
('10001457','K. Lakshmi Nagaveni','klnveni@nmdc.co.in','Dy.General Manager','M08-DGM','HR'),
('10001527','Kota Sreedhar','sreedhark@nmdc.co.in','Asst.General Manager','M07-AGM','Survey-11C'),
('10001533','N L Nagendra Singh','snagendra@nmdc.co.in','Asst.General Manager','M07-AGM','Works'),
('10001541','SAROJ KUMAR SAHU','drsksahu@nmdc.co.in','Dy.General Manager','M08-DGM','Chemical Lab'),
('10001572','Sukhram Gawde','srgawde@nmdc.co.in','Manager','M05-Mgr','CSR'),
('10001589','Krishna Singh','krishnasingh@nmdc.co.in','Jr.Officer','JO-Junior Officer','MECH. SERVICES-SC-11C'),
('10001607','Dhiren Bhushan','dhirenbhushan@nmdc.co.in','General Manager','M09-GM','MINING-Mine Office 14'),
('10001628','Shivdas ATIT Chikate','sachikate@nmdc.co.in','Dy.General Manager','M08-DGM','C&IT'),
('10001633','Ashish Prabhakar Zadpe','ashishpzadpe@nmdc.co.in','Dy.General Manager','M08-DGM','Works'),
('10001675','Samu Samson Nag','ssnag@nmdc.co.in','General Manager','M09-GM','PLANT (MECH.)-Plant Office'),
('10001699','Dasari Rama Mohan Rao','drmrao@nmdc.co.in','Senior Manager','M06-SM','PLANT (ELECT.)-CP(E)-11C'),
('10001775','Daktar Mandi','daktarmandi@nmdc.co.in','Asst.General Manager','M07-AGM','MINING 11B-Mining'),
('10001866','Harishankar Rawal','hsrawal@nmdc.co.in','Dy.General Manager','M08-DGM','T&S,E-Trg.Inst'),
('10001868','Tapas Kumar Mondal','tkmondal@nmdc.co.in','Dy.General Manager','M08-DGM','MINING 11C-Mining'),
('10001877','Narendra Kumar Dande','nkdande@nmdc.co.in','Dy.General Manager','M08-DGM','MECH. SERVICES-HRS-14'),
('10001878','Mudavath Balu','mbalu@nmdc.co.in','Asst.General Manager','M07-AGM','PLANT (MECH.)-CP&DH(M)-11B'),
('10001895','G Imtiaz','g.imtiaz@nmdc.co.in','Asst.General Manager','M07-AGM','MECH. SERVICES-HRS-14'),
('10001898','Harish T','tharish@nmdc.co.in','Asst.General Manager','M07-AGM','MECH. SERVICES-S.M.Office'),
('10001913','Devale Nagaraja Rao','dnrao@nmdc.co.in','Manager','M05-Mgr','MECH. SERVICES-FRS-14'),
('10001914','Kumaravelu Shameer','shameer1322@nmdc.co.in','Senior Manager','M06-SM','PLANT (MECH.)-SP-I(M)'),
('10001924','Ashok Kumar Thakur','athakur@nmdc.co.in','Asst.General Manager','M07-AGM','Vigilance'),
('10001927','Prabhuraj Bharabhari','prabhurajb81@nmdc.co.in','Senior Manager','M06-SM','PLANT (MECH.)-LP(M)'),
('10001941','Manish Kumar Dhruw','manishdhruw@nmdc.co.in','Deputy Manager','M04-DM','ELECT SERVICES-FES-14'),
('10001947','Bhopendra Kumar Kalihari','bkkalihari@nmdc.co.in','Asst.General Manager','M07-AGM','PLANT (ELECT.)-SP-I(E)'),
('10001949','Jangam Sreenivasa Rao','jsreenivasa@nmdc.co.in','Asst.General Manager','M07-AGM','MECH. SERVICES-Auto Shop'),
('10001968','Vinod Kumar Chaturvedi','chaturvedivk@nmdc.co.in','Asst.General Manager','M07-AGM','Works'),
('10001974','Vikram Dehriya','vikram.dehriya@nmdc.co.in','Jr.Officer','JO-Junior Officer','PLANT (ELECT.)-DH(E)-11C'),
('10001977','Mahesh Kumar Verma','mkverma@nmdc.co.in','Asst.General Manager','M07-AGM','Geology-Q.Control'),
('10001985','K.Chandra Mouli','chandramoulikadiam@gmail.com','Assistant Manager','M03-AM','MECH. SERVICES-HEM,KDL'),
('10001988','Arvind Kumar Patle','arvind.kumar@nmdc.co.in','Jr.Officer','JO-Junior Officer','PLANT (MECH.)-DH(M)-14'),
('10001991','Chetan Wakde','chetanwakde@nmdc.co.in','Jr.Officer','JO-Junior Officer','MECH. SERVICES-FRS-11B'),
('10001992','Manoj Kumar Vishwakarma','manojvishwakarma@nmdc.co.in','Jr.Officer','JO-Junior Officer','PLANT (MECH.)-DH(M)-11C'),
('10001993','Tapan Kumar Paul','tapankrpaul@nmdc.co.in','Assistant Manager','M03-AM','PLANT (MECH.)-DH(M)-11C'),
('10001994','Nitish Kumar Biswas','nitishkrbiswas@nmdc.co.in','Assistant Manager','M03-AM','PLANT (MECH.)-CP(M)-11C'),
('10002006','Dinesh Thakur','dineshthakur@nmdc.co.in','Senior Manager','M06-SM','Works'),
('10002010','Mohd Moulana Sayyad Baba','mdmsbaba@nmdc.co.in','Dy.General Manager','M08-DGM','PLANT (MECH.)-LP(M)'),
('10002011','Kandude Naresh Kumar','knaresh@nmdc.co.in','Asst.General Manager','M07-AGM','Contract'),
('10002012','Takeshwar Lal Markam','takeshwar@nmdc.co.in','Asst.General Manager','M07-AGM','MINING 14-Mining'),
('10002036','Ram Kumar Dewangon','dewangonrk@nmdc.co.in','Asst.General Manager','M07-AGM','ELECT SERVICES-FES-11C'),
('10002060','Purushottam  Sahu','purushottamsahu@nmdc.co.in','Jr.Officer','JO-Junior Officer','MECH. SERVICES-HRS-14'),
('10002062','Virendra Kumar Vaishnav','virendra.vaishnav@nmdc.co.in','Jr.Officer','JO-Junior Officer','MECH. SERVICES-HRS-14'),
('10002065','Manoj Kumar Bhagat','manojbhagatvp33@nmdc.co.in','Jr.Officer','JO-Junior Officer','PLANT (MECH.)-CP(M)-14'),
('10002068','Ashish Kumar Kesharwani','ashishkesh@nmdc.co.in','Deputy Manager','M04-DM','PLANT (ELECT.)-CP&DH(E)-14'),
('10002072','Sachin Kumar Shrivastava','sachin@nmdc.co.in','Deputy Manager','M04-DM','PLANT (ELECT.)-SP-I(E)'),
('10002073','Vijendra Kumar Mahanand','vkmahanand@nmdc.co.in','Jr.Officer','JO-Junior Officer','MECH. SERVICES-FRS-11C'),
('10002076','Virendra Kumar Bande','vkbande@nmdc.co.in','Asst.General Manager','M07-AGM','PLANT (MECH.)-SP-I(M)'),
('10002077','Anil Nalam','anilnalam@nmdc.co.in','Asst.General Manager','M07-AGM','PLANT (MECH.)-CP(M)-11C'),
('10002078','Ravi Singh','ravisingh@nmdc.co.in','Asst.General Manager','M07-AGM','Contract'),
('10002089','Animesh Prasad','animeshprasad@nmdc.co.in','Asst.General Manager','M07-AGM','MECH. SERVICES-FRS-11B'),
('10002214','S Shashi Kumar','shashikumar@nmdc.co.in','Dy.General Manager','M08-DGM','ELECT SERVICES'),
('10002215','G Channabasappa','channabasappa@nmdc.co.in','Dy.General Manager','M08-DGM','PLANT (ELECT.)-CP(E)-11C'),
('10002216','Sumit Arora','sumitarora@nmdc.co.in','Asst.General Manager','M07-AGM','ELECT SERVICES-ERS'),
('10002217','Abhimanyu Sahu','asahu@nmdc.co.in','Dy.General Manager','M08-DGM','MINING-Blasting'),
('10002218','Sushant Ramteke','sramteke@nmdc.co.in','Dy.General Manager','M08-DGM','MINING 14-Mining'),
('10002221','B. Hari Gopal','bharigopal@nmdc.co.in','Dy.General Manager','M08-DGM','MINING 11C-Mining'),
('10002223','Nageshwar Nandal','nnandal@nmdc.co.in','Dy.General Manager','M08-DGM','MINING 11B-Mining'),
('10002225','Ritesh Misra','rmishra@nmdc.co.in','Dy.General Manager','M08-DGM','MINING-Mine Planning cell'),
('10002248','Kanwar Pal Singh','kpsingh@nmdc.co.in','General Manager','M09-GM','Production'),
('10002311','Deepak Sahu','dsahu75@rediffmail.com','Manager','M05-Mgr','ELECT SERVICES-TS/MSS'),
('10002357','Prashant Kumar Verma','pkverma@nmdc.co.in','Dy.General Manager','M08-DGM','Works'),
('10002361','Avaneesh Sharma','asharma@nmdc.co.in','Dy.General Manager','M08-DGM','T&S,E-Environment'),
('10002400','Shailendra Soni','sshailendra@nmdc.co.in','Asst.General Manager','M07-AGM','HR'),
('10002401','Ajay Bage','bajay@nmdc.co.in','Senior Manager','M06-SM','HR'),
('10002409','Ritayan Goswami','gritayan@nmdc.co.in','General Manager','M09-GM','Geology-Q.Control'),
('10002412','Vishal Devare','vishaldavare@nmdc.co.in','Dy.General Manager','M08-DGM','PLANT (MECH.)-SP-II(M)'),
('10002414','Rajkumar Manda','mrajkumar@nmdc.co.in','Asst.General Manager','M07-AGM','T&S,E-Trg.Inst'),
('10002417','Rajendra Kumar Sahu','rajendraks@nmdc.co.in','Dy.General Manager','M08-DGM','MINING 11B-Mining'),
('10002419','Rajesh Kumar Kondu','krkumar@nmdc.co.in','Dy.General Manager','M08-DGM','MINING 14-Mining'),
('10002424','Manoj Valentine Lal','mvlal@nmdc.co.in','Chief Medical Officer','M08-DGM','Hospital'),
('10002434','Prem Lal Chandrawanshee','premlal@nmdc.co.in','Asst.General Manager','M07-AGM','ELECT SERVICES-FES-11B'),
('10002438','Sugali Surendra Naik','sugalisn@nmdc.co.in','Senior Manager','M06-SM','ELECT SERVICES-FES-14'),
('10002444','Praveen Kumar Sharma','psharma@nmdc.co.in','Asst.General Manager','M07-AGM','PLANT (ELECT.)-CP&DH(E)-11B'),
('10002445','Chandra Mohan Jha','chandramohanzha@nmdc.co.in','Asst.General Manager','M07-AGM','ELECT SERVICES-FES-14'),
('10002552','Srawan Kumar Jagat','srawanjagat@nmdc.co.in','Manager','M05-Mgr','PLANT (MECH.)-LP(M)'),
('10002553','Amit Sonkar','amitsonkar@nmdc.co.in','Jr.Officer','JO-Junior Officer','MECH. SERVICES-Transport'),
('10002555','Shaik Gowsh Ahemmed','shaik.ahemmed@nmdc.co.in','Jr.Officer','JO-Junior Officer','PLANT (MECH.)-LP(M)'),
('10002556','Rajendra Kumar Sidhu','rajendra.sidhu@nmdc.co.in','Jr.Officer','JO-Junior Officer','MECH. SERVICES-FRS-11C'),
('10002565','Rohit Prasad','rohitprasad@nmdc.co.in','Jr.Officer','JO-Junior Officer','PLANT (MECH.)-CP(M)-14'),
('10002639','Srikanth Basani','srikanth_basani@nmdc.co.in','Asst.General Manager','M07-AGM','Geology-Prod.Plg'),
('10002642','Manisha Lal','manishalal@nmdc.co.in','Chief Medical Officer','M08-DGM','Hospital'),
('10002682','Toran Kumar Dhruw','torankumardhruw@gmail.com','Jr.Officer','JO-Junior Officer','PLANT (ELECT.)-CP&DH(E)-11B'),
('10002683','Sukdew Kumar Shrey','sukdewkumar@nmdc.co.in','Jr.Officer','JO-Junior Officer','ELECT SERVICES-FES-11B'),
('10002691','Nathela Ram Netam','nathelaram@nmdc.co.in','Jr.Officer','JO-Junior Officer','PLANT (ELECT.)-SP-I(E)'),
('10002693','Mahesh Kumar Singh','maheshkumar_singh@nmdc.co.in','Senior Manager','M06-SM','Geology-Geology-11C'),
('10002697','Anil Deshmukh','anildeshmukh@nmdc.co.in','Asst.General Manager','M07-AGM','MINING-Kumhar Marenga'),
('10002701','Shrikant Gabhne','sgabhane@nmdc.co.in','Dy.General Manager','M08-DGM','MINING 14-Mining'),
('10002713','Inteti Sree Harsha','sreeharsha@nmdc.co.in','Asst.General Manager','M07-AGM','MINING 11C-Mining'),
('10002715','Varun Kumar Yadav','varun.kumar@nmdc.co.in','Asst.General Manager','M07-AGM','PLANT (ELECT.)-LP(E)'),
('10002716','Raj Kumar Palli','rajkumar.p@nmdc.co.in','Asst.General Manager','M07-AGM','PLANT (ELECT.)-DH(E)-11C'),
('10002728','Praveen Patle','ppatle@nmdc.co.in','Asst.General Manager','M07-AGM','C&IT'),
('10002764','Lala Ram Sahu','lalasahu.nmdc17@gmail.com','Jr.Officer','JO-Junior Officer','PLANT (ELECT.)-CP&DH(E)-14'),
('10002770','K Suresh Kumar','sureshd786@nmdc.co.in','Senior Manager','M06-SM','Works'),
('10002771','Lakavath Shivalal','lakavath.shivalal644@gmail.com','Jr.Officer','JO-Junior Officer','PLANT (ELECT.)-SP-I(E)'),
('10002809','Sandip Kumar Bansod','sandipbansod11@nmdc.co.in','Manager','M05-Mgr','ELECT SERVICES-FES-11B'),
('10002816','SB Venkateswarlu','sbvenkat@nmdc.co.in','Asst.General Manager','M07-AGM','CIVIL-Civil Office'),
('10002817','Laxman Kumar Pradhan','lkpradhan@nmdc.co.in','Dy.General Manager','M08-DGM','CIVIL-Civil Office'),
('10002830','Bhajan Lal Sao','sbhajanlal@nmdc.co.in','Asst.General Manager','M07-AGM','PLANT (ELECT.)-LP(E)'),
('10002833','Faneendra Kumar Sahu','faneendra@nmdc.co.in','Asst.General Manager','M07-AGM','MINING-Mine Planning cell'),
('10002836','Sravan Kumar Polepaka','psravan@nmdc.co.in','Asst.General Manager','M07-AGM','MINING 11B-Mining'),
('10002837','Bandaru Syam Prasad','bsyamprasad@nmdc.co.in','Asst.General Manager','M07-AGM','MINING 11B-Mining'),
('10002838','Naveen Das','naveen@nmdc.co.in','Dy.General Manager','M08-DGM','PLANT (MECH.)-Plant Office'),
('10002848','Amit Kumar Saw','aksaw@nmdc.co.in','Asst.General Manager','M07-AGM','Geology-Q.Control'),
('10002956','Anil Kumar Haribyasi','anil1933.ak@gmail.com','Jr.Officer','JO-Junior Officer','MECH. SERVICES-HRS-14'),
('10002959','Susheel Kumar Sonker','susheel2015@rediffmail.com','Jr.Officer','JO-Junior Officer','MECH. SERVICES-FRS-14'),
('10002960','Bhupesh Johri','bhupeshjohri99@gmail.com','Jr.Officer','JO-Junior Officer','MECH. SERVICES-FRS-11B'),
('10003008','Salkhan Marndi','salkhan82@gmail.com','Jr.Officer','JO-Junior Officer','MECH. SERVICES-FRS-14'),
('10003095','Amrita Shrivastava','amrita@nmdc.co.in','Joint Chief Medical Officer','M07-AGM','Hospital'),
('10003097','Rajnish Shah','manupriya@nmdc.co.in','Chief Medical Officer','M08-DGM','Hospital'),
('10003106','Salil Srivastava','salilsrivastava@nmdc.co.in','Chief Medical Officer','M08-DGM','Hospital'),
('10003107','Khushboo Shrivastava','khusboo@nmdc.co.in','Deputy Chief Medical Officer','M06-SM','Hospital'),
('10003112','Kandukuri Bhanu Prasad','bhanuprasad@nmdc.co.in','Asst.General Manager','M07-AGM','Finance'),
('10003156','Santosh Kumar','santoshk@nmdc.co.in','Asst.General Manager','M07-AGM','ELECT SERVICES'),
('10003208','Anju Shah','anjushah@nmdc.co.in','Chief Medical Officer','M08-DGM','Hospital'),
('10003266','Nishchal Chowdhary','nishchal_chowdary@nmdc.co.in','Dy.General Manager','M08-DGM','PLANT (MECH.)-Plant Office'),
('10003338','Rupesh Kumar','rupesh@nmdc.co.in','Dy.General Manager','M08-DGM','MINING-Blasting'),
('10003365','Prashant','prashanth@nmdc.co.in','Asst.General Manager','M07-AGM','PLANT (MECH.)-LP(M)'),
('10003370','Saurabh Kumar','saurabhb2661@nmdc.co.in','Asst.General Manager','M07-AGM','MECH. SERVICES-Auto Shop'),
('10003372','Arvind Kumar Sahu','arvindksahu@nmdc.co.in','Asst.General Manager','M07-AGM','PLANT (MECH.)-SP-II(M)'),
('10003374','Md.Mehboob Ullah','mehboobullah@nmdc.co.in','Asst.General Manager','M07-AGM','Material Management-C.S.D.,KDL'),
('10003549','Labbo Tande','labbotande@nmdc.co.in','Senior Manager','M06-SM','PLANT (MECH.)-SP-I(M)'),
('10003555','Prem Kumar Vaishnaw','vpremkumar@nmdc.co.in','Senior Manager','M06-SM','MECH. SERVICES-FRS-11B'),
('10003560','Ritesh Kumar','ritesh.netam@nmdc.co.in','Senior Manager','M06-SM','MECH. SERVICES-FRS-11B'),
('10003564','Ashok Kumar Gupta','akgupta@nmdc.co.in','Senior Manager','M06-SM','PLANT (MECH.)-DH(M)-11C'),
('10003576','Rupak Kumar Burman','rupakburman@nmdc.co.in','Dy.General Manager','M08-DGM','MECH. SERVICES-FRS-14'),
('10003577','Prakash T','tprakash@nmdc.co.in','Asst.General Manager','M07-AGM','MECH. SERVICES-FRS-14'),
('10003580','Mahesh Kumar Sambeta','mahesh1985@nmdc.co.in','Senior Manager','M06-SM','CIVIL-Civil Maint O/T'),
('10003602','Dhananjay Kumar Shrivastava','dhananjay@nmdc.co.in','Joint Chief Medical Officer','M07-AGM','Hospital'),
('10003604','s.v.n Sai Sobhan katuru','saisobhan@nmdc.co.in','Asst.General Manager','M07-AGM','Chemical Lab'),
('10003610','Rajesh Singh','rajesh.singh@nmdc.co.in','Joint Chief Medical Officer','M07-AGM','Hospital'),
('10003619','Patil Sanjay Nilkanth','patilsn@nmdc.co.in','Asst.General Manager','M07-AGM','HR'),
('10003621','Ram Gopal Pandey','ram.gopal@nmdc.co.in','Deputy Manager','M04-DM','MINING-Blasting'),
('10003768','Abinash Swain','abinashswain@nmdc.co.in','Dy.General Manager','M08-DGM','PLANT (MECH.)-CP(M)-11C'),
('10003778','Rajesh Somala','srajesh@nmdc.co.in','Asst.General Manager','M07-AGM','Chemical Lab'),
('10003779','Manas Bharti','manasbharti@nmdc.co.in','Senior Manager','M06-SM','T&S,E-Trg.Inst'),
('10003816','Ashish Shrivastava','ashish@nmdc.co.in','Asst.General Manager','M07-AGM','Chemical Lab'),
('10003823','Swaroop Koneru','swaroopkoneru@nmdc.co.in','Asst.General Manager','M07-AGM','Chemical Lab'),
('10003828','Yashwant Kumar Dashora','ykdashora@nmdc.co.in','Dy.General Manager','M08-DGM','Chemical Lab'),
('10003834','Aman Kumar Hazarika','akhazarika@nmdc.co.in','Senior Manager','M06-SM','Finance'),
('10003836','Abhishek Kumar Prasad','akprasad@nmdc.co.in','Senior Manager','M06-SM','Works'),
('10003872','Bula Srinivas','bulasrinivas@nmdc.co.in','Manager','M05-Mgr','CIVIL-Civil Maint O/T'),
('10003876','Susheel Chandra Gupta','scgupta@nmdc.co.in','Asst.General Manager','M07-AGM','Material Management'),
('10003879','Sandeep','sandeep@nmdc.co.in','Manager','M05-Mgr','CSR'),
('10003900','Digvijay Jaiswal','digvijay.jaiswal@nmdc.co.in','Senior Manager','M06-SM','Works'),
('10003924','Avinash Agarwal','avinash-agarwal@nmdc.co.in','Asst.General Manager','M07-AGM','Works'),
('10003954','Dheeraj Narayana Swamy','dnswamy@nmdc.co.in','Asst.General Manager','M07-AGM','Finance'),
('10003961','Mohd Tanwir Jawed','tanwirjawed@nmdc.co.in','Dy.General Manager','M08-DGM','HR'),
('10003964','Narendra D Ambade','narendra@nmdc.co.in','Asst.General Manager','M07-AGM','HR'),
('10004036','Vishad Vats','vatsight01@nmdc.co.in','Senior Manager','M06-SM','T&S,E-Environment'),
('10004042','D.Bhaskar Rao','dbhaskarrao@nmdc.co.in','Senior Manager','M06-SM','CIVIL'),
('10004043','Yogesh Kumar Nirmalkar','yogeshnirmalkar@nmdc.co.in','Asst.General Manager','M07-AGM','Works'),
('10004053','Pawan Kumar Malav','pawanmalav@nmdc.co.in','Asst.General Manager','M07-AGM','MINING 11C-Mining'),
('10004062','Abhishek Kumar','drabhishek2001@nmdc.co.in','Chief Medical Officer','M08-DGM','Hospital'),
('10004063','Homa','drhoma2007@nmdc.co.in','Joint Chief Medical Officer','M07-AGM','Hospital'),
('10004067','Ramkrishna Kumbhakar','dr.rm2008@nmdc.co.in','Joint Chief Medical Officer','M07-AGM','Hospital'),
('10004092','Narendra Shekhar Pawar','nspawar@nmdc.co.in','Dy.General Manager','M08-DGM','PLANT (MECH.)-CP(M)-14'),
('10004095','Ranjit Eknathrao Dhiware','ranjitdhiware@nmdc.co.in','Asst.General Manager','M07-AGM','Material Management'),
('10004145','Mritunjay Kumar Choudhary','mayank@nmdc.co.in','Joint Chief Medical Officer','M07-AGM','Hospital'),
('10004149','Saurabh Khare','saurabh.khare@nmdc.co.in','Asst.General Manager','M07-AGM','MINING-Blasting'),
('10004168','Dileep Kumar Chaudhari','dileepkumar@nmdc.co.in','Manager','M05-Mgr','MECH. SERVICES-SC-11C'),
('10004169','Ishwar Kumar Sahu','sahu.ishwar@nmdc.co.in','Manager','M05-Mgr','PLANT (MECH.)-DH(M)-11C'),
('10004170','Anil Kumar Jaiswal','aniljaiswal@nmdc.co.in','Manager','M05-Mgr','PLANT (ELECT.)-SP-II(E)'),
('10004171','Lokesh Kumar Korram','lokesh.korram@nmdc.co.in','Manager','M05-Mgr','PLANT (MECH.)-CP&DH(M)-11B'),
('10004172','Jitendra Kumar Diwakar','diwakar.mech08@nmdc.co.in','Manager','M05-Mgr','PLANT (MECH.)-SP-II(M)'),
('10004173','Gulshan Zameer Shah','gulshan@nmdc.co.in','Manager','M05-Mgr','MECH. SERVICES-FRS-11C'),
('10004174','Rahul Kesharwani','rahulk1989@nmdc.co.in','Manager','M05-Mgr','MECH. SERVICES-FRS-14'),
('10004175','Akash Patnaik','akash.patnaik@nmdc.co.in','Deputy Manager','M04-DM','T&S,E-Trg.Inst'),
('10004176','Bhorprakash Sahu','bhorprakash22@nmdc.co.in','Manager','M05-Mgr','PLANT (MECH.)-LP(M)'),
('10004177','Deepak Kumar','deepakkumar90@nmdc.co.in','Manager','M05-Mgr','MECH. SERVICES-HRS-14'),
('10004178','Ashish Kumar Bhowmick','ashish1990@nmdc.co.in','Manager','M05-Mgr','PLANT (ELECT.)-SP-II(E)'),
('10004179','Praveen Kumar Sahu','praveen22@nmdc.co.in','Manager','M05-Mgr','ELECT SERVICES-FES-11C'),
('10004180','Nishant Ganguly','nishantganguly@nmdc.co.in','Manager','M05-Mgr','PLANT (ELECT.)-CP&DH(E)-11B'),
('10004181','Vijay Barai','vijaybarai@nmdc.co.in','Manager','M05-Mgr','PLANT (MECH.)-CP(M)-11C'),
('10004184','Santhosh Kumar Vardhanapu','jipmersanthosh@nmdc.co.in','Deputy Chief Medical Officer','M06-SM','Hospital'),
('10004186','Rishi Kumar Jaiswal','rishijaiswal@nmdc.co.in','Asst.General Manager','M07-AGM','MINING 14-Mining'),
('10004238','Pramod Kumar','pramod15@nmdc.co.in','Asst.General Manager','M07-AGM','HR'),
('10004242','Parthipan.T','parthipant@nmdc.co.in','Assistant Manager','M03-AM','PLANT (ELECT.)-DH(E)-11C'),
('10004244','Neetu Dewangan','neetu@nmdc.co.in','Manager','M05-Mgr','Material Management'),
('10004255','Vishal Vinayak Kamble','vishaalkamble576@gmail.com','Manager','M05-Mgr','MINING 11B-Mining'),
('10004256','Khinjan Lal Som','khinjansom@gmail.com','Manager','M05-Mgr','MINING 11B-Mining'),
('10004257','Sumit  Singh','sumit1979@nmdc.co.in','Deputy Manager','M04-DM','MINING 11C-Mining'),
('10004258','Manas Ranjan Mohanty','mrmohanty@nmdc.co.in','Deputy Manager','M04-DM','MINING 11B-Mining'),
('10004259','Srinivas Guguloth','srinunaik@nmdc.co.in','Manager','M05-Mgr','PLANT (ELECT.)-LP(E)'),
('10004271','Sunay Gupta','sunay@nmdc.co.in','Manager','M05-Mgr','ELECT SERVICES-FES-11C'),
('10004272','Asim Kumar Sahoo','kumarasim@nmdc.co.in','Manager','M05-Mgr','PLANT (ELECT.)-SP-I(E)'),
('10004274','ABHIJIT GHOSH','aghosh@nmdc.co.in','Asst.General Manager','M07-AGM','HR'),
('10004277','Hari Narayan Tiwari','hnt@nmdc.co.in','Senior Manager','M06-SM','Works'),
('10004279','Abhijeet Mishra','abhijeet@nmdc.co.in','Senior Manager','M06-SM','HR'),
('10004283','Prashant Shingdilwar','shingdilwar@nmdc.co.in','Deputy Chief Medical Officer','M06-SM','Hospital'),
('10004300','Sunil Kumar Swarnkar','sunil.kumar@nmdc.co.in','Assistant Manager','M03-AM','MECH. SERVICES-HEM,KDL'),
('10004302','Prashant Yashwantrao Raut','prashantraut@nmdc.co.in','Manager','M05-Mgr','MINING 11C-Mining'),
('10004307','Naveen Kumar','naveen.kumar@nmdc.co.in','Asst.General Manager','M07-AGM','HR'),
('10004308','Ashok Kumar Netam','netamashok324@gmail.com','Manager','M05-Mgr','MINING 11C-Mining'),
('10004309','Vinod Kumar Dilliwar','vinod.dilliwar@nmdc.co.in','Manager','M05-Mgr','MINING 14-Mining'),
('10004311','Maricherla Tirupathi Rao .','mtirupathirao@nmdc.co.in','Dy.General Manager','M08-DGM','HR'),
('10004333','Dipak Kumar Pal','dkpal@nmdc.co.in','Asst.General Manager','M07-AGM','HR'),
('10004353','Somnath Ghosh','somnath.ghosh@nmdc.co.in','Manager','M05-Mgr','Finance'),
('10004359','Jai Kumar TIWARY','jaitiwary@nmdc.co.in','Senior Manager','M06-SM','Geology-Q.Control'),
('10004366','Ravindra Kumar Sahu','ravindraksahu@nmdc.co.in','Senior Manager','M06-SM','Finance'),
('10004372','Panchanan Das','panchanan.das@nmdc.co.in','Senior Manager','M06-SM','Geology-Geology-14'),
('10004376','Sudhir Ganpat Gaikwad','sudhir.gaikwad@nmdc.co.in','Asst.General Manager','M07-AGM','Geology-Q.Control'),
('10004459','Balla Appala Naidu','naiducma@nmdc.co.in','Senior Manager','M06-SM','Works'),
('10004474','Praveen Kumar Gujjar','praveengujjar@nmdc.co.in','Deputy Manager','M04-DM','Survey-11C'),
('10004476','Akhila Chandra Padhi','akhilachandrapadhi@nmdc.co.in','Senior Manager','M06-SM','Finance'),
('10004485','Rajesh Kumar','rajeshk@nmdc.co.in','Senior Manager','M06-SM','IE'),
('10004495','Ajay Kumar','ajay.kumar@nmdc.co.in','Senior Manager','M06-SM','HR'),
('10004541','Chandra Shekhar Sahu','cssahu4716@nmdc.co.in','Manager','M05-Mgr','PLANT (ELECT.)-SP-II(E)'),
('10004549','Devendra Singh','devsingh@nmdc.co.in','Senior Manager','M06-SM','C&IT'),
('10004554','Guddeti V S Rama Krishna','gvsrk@nmdc.co.in','Senior Manager','M06-SM','Vigilance'),
('10004555','Debabrota Mondal','debabrota@nmdc.co.in','Senior Manager','M06-SM','T&S,E-Environment'),
('10004570','Baljinder Singh','baljinder@nmdc.co.in','Senior Manager','M06-SM','IE'),
('10004571','Vikas Kumar','vikasismmle@nmdc.co.in','Senior Manager','M06-SM','HOP Sectt.'),
('10004581','Alok Kumar Ranjan','alokr@nmdc.co.in','Senior Manager','M06-SM','MINING-Mine Planning cell'),
('10004596','Nikhil Madane','nikhilmadane@nmdc.co.in','Senior Manager','M06-SM','MECH. SERVICES-FRS-14'),
('10004602','Mummaneni Dilip Chand','dilipchand@nmdc.co.in','Asst.General Manager','M07-AGM','PLANT (MECH.)-CP&DH(M)-11B'),
('10004604','Kandasamy Gopal','kgopal@nmdc.co.in','Asst.General Manager','M07-AGM','MECH. SERVICES-SC-11C'),
('10004607','Sathish S','satish.s@nmdc.co.in','Asst.General Manager','M07-AGM','PLANT (MECH.)-DH(M)-14'),
('10004610','Vipin Verma','vipin20@nmdc.co.in','Senior Manager','M06-SM','Chemical Lab'),
('10004614','Vivek Kumar Raksha','vivekkraksha@nmdc.co.in','Senior Manager','M06-SM','CSR'),
('10004620','Sharad Gupta','sharadg@nmdc.co.in','Senior Manager','M06-SM','Material Management'),
('10004671','Amit Rajaram Fulzele','amit.rf@nmdc.co.in','Senior Manager','M06-SM','Works'),
('10004673','Guguloth Ram Kumar','ramkumar@nmdc.co.in','Manager','M05-Mgr','PLANT (ELECT.)-CP&DH(E)-14'),
('10004675','Vinit Tiwari','vinit@nmdc.co.in','Senior Manager','M06-SM','PLANT (ELECT.)-SP-II(E)'),
('10004677','Upender Rao Konda','upenderrao.konda@nmdc.co.in','Senior Manager','M06-SM','ELECT SERVICES-FES-11B'),
('10004690','Jaka Madhu','jakamadhu@nmdc.co.in','Senior Manager','M06-SM','PLANT (ELECT.)-SP-II(E)'),
('10004710','Prasanna Kumar M S','msprasanna@nmdc.co.in','Asst.General Manager','M07-AGM','MECH. SERVICES-FRS-11C'),
('10004722','Veeranna Vankudoth','veeranna.v@nmdc.co.in','Senior Manager','M06-SM','ELECT SERVICES-Telephone'),
('10004770','Krushna Ballav Acharya','kb.acharya@nmdc.co.in','Senior Manager','M06-SM','PLANT (ELECT.)-LP(E)'),
('10004789','Rahul Satawne','rahul.satawne@nmdc.co.in','Senior Manager','M06-SM','HR'),
('10004807','Gottapu Venkata Murali Krishna','gvmurali@nmdc.co.in','Senior Manager','M06-SM','PLANT (ELECT.)-CP&DH(E)-11B'),
('10004810','Debaranjan Barik','debaranjan.barik@nmdc.co.in','Senior Manager','M06-SM','PLANT (MECH.)-Plant Office'),
('10004811','Vikas Bajpai','vikas.bajpai@nmdc.co.in','Senior Manager','M06-SM','PLANT (MECH.)-LP(M)'),
('10004837','Niraj Kumar Bhatia','niraj.bhatia@nmdc.co.in','Senior Manager','M06-SM','PLANT (ELECT.)-CP&DH(E)-14'),
('10004856','Manish Jha','manishjha@nmdc.co.in','Senior Manager','M06-SM','MECH. SERVICES-SC-11C'),
('10004857','Manku Purna Chandar','purnachandar@nmdc.co.in','Senior Manager','M06-SM','PLANT (MECH.)-SP-I(M)'),
('10004880','Bilkan Kerketta','bilkan90@nmdc.co.in','Senior Manager','M06-SM','MECH. SERVICES-FRS-14'),
('10004942','Satyendra Kumar Gond','vasusatyendra7@nmdc.co.in','Senior Manager','M06-SM','ELECT SERVICES-FES-14'),
('10004948','Vallabhaneni Chaitanya','chaitanyavallabhaneni@nmdc.co.','Senior Manager','M06-SM','Hospital'),
('10004949','Azad Singh  Patel','aspatel@nmdc.co.in','Senior Manager','M06-SM','PLANT (MECH.)-SP-I(M)'),
('10005261','Abhishek Prabhat','abhishekprabhat02@nmdc.co.in','Deputy Manager','M04-DM','MECH. SERVICES-HRS-14'),
('10005272','Raju Rathee','rajurathee39@nmdc.co.in','Deputy Manager','M04-DM','MECH. SERVICES-Auto Shop'),
('10005276','Apurwa Bhattacharya','apurwa.bhattacharya@nmdc.co.in','Deputy Manager','M04-DM','MINING 14-Mining'),
('10005282','Nabghan Raut','nabghanraut@nmdc.co.in','Deputy Manager','M04-DM','MINING 11B-Mining'),
('10005288','Basant Kumar Sidar','bksidar88@nmdc.co.in','Deputy Manager','M04-DM','MINING 11C-Mining'),
('10005355','Isha Shrivastava','shrivastavaeye@nmdc.co.in','Deputy Manager','M04-DM','Material Management'),
('10005672','Sandeepta Kumar Mohanty','sandeep.mining@nmdc.co.in','Manager','M05-Mgr','MINING 14-Mining'),
('10005675','Dambarudhar Sahoo','dambarudhar.sahoo@nmdc.co.in','Manager','M05-Mgr','MINING 11C-Mining'),
('10005681','Rakesh Kumar Jaiswal','rkjaiswal@nmdc.co.in','Manager','M05-Mgr','Geology-Prod.Plg'),
('10005682','Debabrata Sarkar','debusarkar@nmdc.co.in','Manager','M05-Mgr','Geology-Prod.Plg'),
('10005683','Dipankar Chakraborty','cdipankar91@nmdc.co.in','Manager','M05-Mgr','MINING 11C-Mining'),
('10005738','Sourabh Pandit','sourabhpandit@nmdc.co.in','Deputy Manager','M04-DM','Finance'),
('10005739','Akash Kumar Dalai','akashkumardalai@nmdc.co.in','Deputy Manager','M04-DM','Finance'),
('10005749','Lalit Ujjwal','lalit.ujjwal@nmdc.co.in','Deputy Manager','M04-DM','PLANT (ELECT.)-LP(E)'),
('10005764','Naveen Runku','naveenrunku@nmdc.co.in','Deputy Manager','M04-DM','Material Management'),
('10005773','Abhisheka','abhisheka@nmdc.co.in','Deputy Manager','M04-DM','PLANT (MECH.)-SP-II(M)'),
('10005775','Kona Bhushana Rao','konabhushana@nmdc.co.in','Deputy Manager','M04-DM','PLANT (MECH.)-CP(M)-11C'),
('10005794','Jaiprakash','jaiprakash@nmdc.co.in','Deputy Manager','M04-DM','MINING 14-Mining'),
('10005799','Himanshu Shekhar','himanshu.shekhar@nmdc.co.in','Deputy Manager','M04-DM','MINING 11B-Mining'),
('10005801','Srinu Manikala','srinumanikala@nmdc.co.in','Deputy Manager','M04-DM','MINING 11C-Mining'),
('10005803','Pradeep Kumar Chaurasia','cmapradeep@nmdc.co.in','Deputy Manager','M04-DM','Works'),
('10005821','Simhadri Saicharan','simhadri@nmdc.co.in','Assistant Manager','M03-AM','PLANT (MECH.)-SP-II(M)'),
('10005822','VASANTADA KIRAN RAO','vkiran@nmdc.co.in','Assistant Manager','M03-AM','PLANT (MECH.)-CP&DH(M)-11B'),
('10005823','PRAKASH PATEL','prakashpatel@nmdc.co.in','Assistant Manager','M03-AM','MECH. SERVICES-FRS-11B'),
('10005825','GAURAV KUMAR','gaurav.kumar@nmdc.co.in','Assistant Manager','M03-AM','PLANT (ELECT.)-LP(E)'),
('10005826','NILESH SONI','nileshsoni@nmdc.co.in','Assistant Manager','M03-AM','ELECT SERVICES-FES-11C'),
('10005832','SAURABH KUMAR','saurabh.kumar@nmdc.co.in','Assistant Manager','M03-AM','CIVIL-Civil Maint O/T'),
('10005833','SHRAVAN KUMAR NISHAD','shravannishad@nmdc.co.in','Assistant Manager','M03-AM','MINING 11C-Mining'),
('10005834','SUSHIL KUMAR JAISWAL','sushilkr@nmdc.co.in','Assistant Manager','M03-AM','ELECT SERVICES-FES-11C'),
('10005835','PENDYALA SHRAVAN KUMAR','pshravan372@nmdc.co.in','Assistant Manager','M03-AM','PLANT (ELECT.)-CP(E)-11C'),
('10005837','SURAJ RAMKRUSHNA SHIRBHATE','surajshirbhate@nmdc.co.in','Assistant Manager','M03-AM','MINING 11C-Mining'),
('10005838','DIPTIRANJAN SAHOO','diptiranjan@nmdc.co.in','Assistant Manager','M03-AM','MINING 11B-Mining'),
('10005839','KONETI HEMA SUNDAR','hemasundar.k5@nmdc.co.in','Assistant Manager','M03-AM','PLANT (MECH.)-LP(M)'),
('10005847','VELUTURI VENKATA SAI SUDHA','vvssudha@nmdc.co.in','Assistant Manager','M03-AM','PLANT (MECH.)-Plant Office'),
('10005940','TAKSANDE AKSHU DILIP','akshu.taksande@nmdc.co.in','Assistant Manager','M03-AM','MINING 11B-Mining'),
('10006104','Raj Kumar Pandey','rajkumar.pandey@nmdc.co.in','Jr.Officer','JO-Junior Officer','MECH. SERVICES-Auto Shop'),
('10006109','Naveen Kumar Dilliwar','naveen.dilliwar@nmdc.co.in','Jr.Officer','JO-Junior Officer','PLANT (MECH.)-SP-II(M)'),
('10006110','Shubham Singh','shubhamsingh.geo@nmdc.co.in','Jr.Officer','JO-Junior Officer','Geology-Q.Control'),
('10006111','Harsh Sahu','harsh.sahu@nmdc.co.in','Jr.Officer','JO-Junior Officer','CIVIL-Civil Maint.Ht'),
('10006112','Yugal Kishor Sahu','yugalkishor@nmdc.co.in','Jr.Officer','JO-Junior Officer','PLANT (ELECT.)-CP&DH(E)-14'),
('10006129','Rajesh Kumar Sahu','rajesh.sahu@nmdc.co.in','Jr.Officer','JO-Junior Officer','PLANT (MECH.)-CP&DH(M)-11B'),
('10006130','Emanuel Tirkey','emanuel.tirkey@nmdc.co.in','Jr.Officer','JO-Junior Officer','MECH. SERVICES-SC-11C'),
('10006131','Manish Goal','gmanish@nmdc.co.in','Jr.Officer','JO-Junior Officer','ELECT SERVICES-FES-14'),
('10006133','Suggala Narendar','narendar.suggala@nmdc.co.in','Jr.Officer','JO-Junior Officer','MINING 11C-Mining'),
('10006135','Rahul Kumar Nirala','rahulkumarnirala@nmdc.co.in','Jr.Officer','JO-Junior Officer','PLANT (MECH.)-DH(M)-14'),
('10006137','Shubham Kumar','shubhamkumar@nmdc.co.in','Jr.Officer','JO-Junior Officer','MINING 14-Mining'),
('10006144','Aditya Mishra','adityamishra@nmdc.co.in','Jr.Officer','JO-Junior Officer','MECH. SERVICES-FRS-11B'),
('10006147','Vinay Verma','vinay.verma@nmdc.co.in','Jr.Officer','JO-Junior Officer','ELECT SERVICES-ERS'),
('10006151','Abhishek Srivastav','abhishek_srivastav@nmdc.co.in','Jr.Officer','JO-Junior Officer','Geology-Prod.Plg'),
('10006152','Ajay Meena','ajaymeena@nmdc.co.in','Jr.Officer','JO-Junior Officer','PLANT (ELECT.)-SP-I(E)'),
('10006155','Kothara Lova Raju','rajumng@nmdc.co.in','Jr.Officer','JO-Junior Officer','MINING 14-Mining'),
('10006157','Sreekanth Chilikeshwarapu','sreekanth@nmdc.co.in','Jr.Officer','JO-Junior Officer','MINING 14-Mining'),
('10006159','Nikhil Kumar','nikhilkumar@nmdc.co.in','Jr.Officer','JO-Junior Officer','MECH. SERVICES-FRS-11C'),
('10006160','Sabbireddy Veera Venkata  Satyanarayana','satyanarayana@nmdc.co.in','Jr.Officer','JO-Junior Officer','PLANT (ELECT.)-CP&DH(E)-11B'),
('10006161','Pranay Manohar Diwe','pranaydiwe@nmdc.co.in','Jr.Officer','JO-Junior Officer','MINING 11B-Mining'),
('10006165','Paritosh Tiwari','paritosh.tiwari@nmdc.co.in','Assistant Manager','M03-AM','HR'),
('10006166','Bikash Kumar Sahoo','bk.sahoo@nmdc.co.in','Assistant Manager','M03-AM','HR'),
('10006174','Rosy Nirola Soren','rn.soren@nmdc.co.in','Assistant Manager','M03-AM','HR'),
('10006183','Kuname Hansdah','k.hansdah@nmdc.co.in','Assistant Manager','M03-AM','HR'),
('10006185','Dalip Kumar','dalip.kumar@nmdc.co.in','Assistant Manager','M03-AM','Material Management'),
('10006190','Nitish Kumar','nitish.kumar@nmdc.co.in','Assistant Manager','M03-AM','Material Management-CSD HT'),
('10006198','Vikrant Vishal','vikrant.vishal@nmdc.co.in','Assistant Manager','M03-AM','MINING 11C-Mining'),
('10006227','Lokeswar Dandi','d.lokeswar@nmdc.co.in','Assistant Manager','M03-AM','PLANT (MECH.)-SP-I(M)'),
('10006229','Trailokya Ranjan Dash','trdash@nmdc.co.in','Manager','M05-Mgr','Finance'),
('10006239','Setty Syam Sundar Yerram','syamsundar@nmdc.co.in','Medical Officer','M05-Mgr','Hospital'),
('10006452','NISHANTH S','nishanth.s@nmdc.co.in','Asst.Medical Officer','M04-DM','Hospital'),
('10006464','Vasudev Joshi','vjoshi01@nmdc.co.in','Assistant Manager','M03-AM','PLANT (ELECT.)-SP-II(E)'),
('10006465','Dharavath Nageshwara Rao','nageshwararao@nmdc.co.in','Assistant Manager','M03-AM','ELECT SERVICES-TS/MSS'),
('10006466','Ravi Kumar','ravikumar21may@nmdc.co.in','Assistant Manager','M03-AM','PLANT (MECH.)-SP-II(M)'),
('10006468','Danveer Dewangan','danveer.dewangan@nmdc.co.in','Assistant Manager','M03-AM','Material Management'),
('10006484','SANDEEP SHARMA','sandeep.sharma@nmdc.co.in','Executive Trainee','ET-Executive Trainee','CIVIL'),
('10006716','ABU BAKAR SAIF','abubakar@nmdc.co.in','Executive Trainee','ET-Executive Trainee','Finance'),
('10006721','PRATHALLA NAGA SAI KIRAN .','nagasaikiran@nmdc.co.in','Executive Trainee','ET-Executive Trainee','PLANT (MECH.)-LP(M)'),
('10006730','Goutham Kumar Chilukuri','gouthamkumar@nmdc.co.in','Executive Trainee','ET-Executive Trainee','Finance'),
('10006737','BIRESWAR DAS','bireswar.das@nmdc.co.in','Executive Trainee','ET-Executive Trainee','Finance'),
('10006738','KALAIKUMAR V','kalaikumar.v@nmdc.co.in','Executive Trainee','ET-Executive Trainee','Works');

